"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'
vimcmd_symbol = '[←](bold yellow)'

[git_branch]
style = "bold fg:#f5c2e7"
symbol = " "
format = "[on](white) [$symbol$branch]($style) "

[git_status]
style = "bold fg:#f5c2e7"
format = "([\\($all_status$ahead_behind\\)]($style) )"
ahead = "⇡"
diverged = "⇕⇡"
behind = "⇣"
staged = "+"
modified = "~"
untracked = "?"
deleted = "x"
conflicted = "!"
renamed = "⇔"

[git_commit]
commit_hash_length = 8
tag_symbol = '🔖 '

[golang]
symbol = ' '
